<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UserSecretsId>aspnet-Award-3936F1D5-5B5A-4AA9-B366-206206B8C15F</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Views\Evaluation\Index - Copy.cshtml" />
    <Content Remove="wwwroot\css\bootstrap-select-country.min.css" />
    <Content Remove="wwwroot\Image\Announcement\81a736ae-51f2-4e64-a955-7e2c239719e8.png" />
    <Content Remove="wwwroot\Image\lang\united-arab-emirates-flag-wave-icon-32.png" />
    <Content Remove="wwwroot\Image\lang\united-arab-emirates-flag-wave-icon-64.png" />
    <Content Remove="wwwroot\Image\lang\united-kingdom-flag-icon-32.png" />
    <Content Remove="wwwroot\Image\lang\united-kingdom-flag-icon-64.png" />
    <Content Remove="wwwroot\Image\lang\united-states-of-america-flag-icon-32.png" />
    <Content Remove="wwwroot\Image\lang\united-states-of-america-flag-icon-64.png" />
    <Content Remove="wwwroot\js\bootstrap-select-country.min.js" />
    <Content Remove="wwwroot\js\bootstrap-select-country.min.js.map" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Chart.js" Version="2.9.3" />
    <PackageReference Include="DotNetZip" Version="1.13.8" />
    <PackageReference Include="Localization.AspNetCore.TagHelpers" Version="0.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.1.5" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.5" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Session" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.1.0-preview1.19506.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.4" />
    <PackageReference Include="Novell.Directory.Ldap.NETStandard" Version="3.0.1" />
    <PackageReference Include="rotativa.aspnetcore" Version="1.2.0-beta" />
    <PackageReference Include="SharpZipLib.NETStandard" Version="1.0.7" />
    <PackageReference Include="System.DirectoryServices" Version="5.0.0-preview.6.20305.6" />
    <!--<PackageReference Include="Novel.Directory.Ldap.NETStandard" Version="3.0.1" />-->
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Award.Core\Award.Core.csproj" />
    <ProjectReference Include="..\Award.Infrastructure\Award.Infrastructure.csproj" />
  </ItemGroup>


  <ItemGroup>
    <EmbeddedResource Update="Resources\Controllers.AccountController.ar.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers.AccountController.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers.AnnouncementController.ar.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers.AnnouncementHomeController.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers.AnnouncementHomeController.ar.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers.AwardsController.ar.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers.AwardsController.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers.CategoriesController.ar.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers.CategoriesController.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers.EvaluationController.ar.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers.EvaluationController.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers.HomeController.ar.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers.HomeController.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers.SectorController.ar.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers.SectorController.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers.SharedController.ar.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers.SharedController.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers.TeamController.ar.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers.TeamController.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers.WinnersController.ar.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Controllers.WinnersController.resx">
      <Generator></Generator>
    </EmbeddedResource>
  </ItemGroup>


  <ItemGroup>
    <Folder Include="wwwroot\Document\Award\temp\" />
    <Folder Include="wwwroot\Document\temp\" />
    <Folder Include="wwwroot\Image\lang\" />
    <Folder Include="wwwroot\Image\NewFolder\" />
    <Folder Include="wwwroot\temp\" />
  </ItemGroup>


  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>


  <ItemGroup>
    <Content Update="wwwroot\Rotativa\wkhtmltopdf.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
